data:
  data_dir: "/g/kreshuk/wies/data/NuInsSeg"
  scratch_data_dir: "/scratch/wies/data"
  copy_to_scratch: true
  tissues: mouse*  # null, string or list of strings (accepts mix of glob patterns and specific names)
  max_images_per_tissue: null
  use_fixed_test_sets: true  # use fixed human_test & mouse_test sets
  
splits:
  train: 0.8
  val: 0.2
  # test: 0.2 # only used when use_fixed_test_sets: false (legacy mode)

model:
  model_name: "stardist-nuinsseg"
  model_dir: "models"
  n_rays: 32
  grid: [2, 2]
  patch_size: [512, 512] # [256, 256]

training:
  epochs: 400
  steps_per_epoch: null  # null = dataset_size / batch_size
  batch_size: 4
  learning_rate: 0.0003

wandb:
  enabled: true
  project: "stardist-nuinsseg"
  entity: null
  run_name: "nuinsseg-mouse" # automatically timestamped
  tags: ["mouse"]
  log_pred_every_n_epochs: 20
  num_val_samples_to_log: 4
  num_test_samples_to_log: 4

gpu:
  device: 5
  memory_limit: null  # memory limit (MB)
